margo/cart/urls.py
from django.urls import path
from .cart_api import *
from .favours_api import *


urlpatterns = [
  # items
  path('get_cart_items_amount/',   get_cart_items_amount,   name='get_cart_items_amount'),
  path('get_cart_items/',          get_cart_items,          name='get_cart_items'),

  path('add_cart_item/',           add_cart_item,           name='add_cart_item'),
  path('remove_cart_item/',        remove_cart_item,        name='remove_cart_item'),

  path('change_cart_item_amount/', change_cart_item_amount, name='change_cart_item_amount'),
  path('clear_cart/',              clear_cart,              name='clear_cart'),
  # favours
  path('get_favours_amount/',      get_favours_amount,      name='get_favours_amount'),
  path('get_favours/',             get_favours,             name='get_favours'),

  path('add_favour/',              add_favour,              name='add_favour'),
  path('remove_favour/',           remove_favour,           name='remove_favour'),

  path('add_favour_to_cart/',      add_favour_to_cart,      name='add_favour_to_cart'),
  path('add_favours_to_cart/',     add_favours_to_cart,     name='add_favours_to_cart'),

  path('add_favour_by_like/',      add_favour_by_like,      name='add_favour_by_like'),
  path('remove_favour_by_like/',   remove_favour_by_like,   name='remove_favour_by_like'),
  
]

margo/constructor/urls.py
from .models import *
from django.shortcuts import render, redirect, reverse
from django import forms 
from django.urls import path, include
from .api import *



urlpatterns = [
  path('set_param/',       set_param,       name='set_param'),
]

margo/constructor/models.py
from django.db import models
from PIL import Image
from django.utils.translation import gettext as _


NAPKIN_STATUS_CHOICES = (
	(_('Принят в обработку'), _('Принят в обработку')),
	(_('Выполняется'), _('Выполняется')),
	(_('Выполнен'), _('Выполнен')),
	# (_('Оплачен'), _('Оплачен')),
)


class Napkin(models.Model):
  sk       = models.CharField(max_length=120, blank=True, null=True)
  final    = models.ImageField(verbose_name=("Финальное изображение"), blank=True, null=True)
  logo     = models.ImageField(blank=True, null=True)
  template = models.ForeignKey('constructor.NapkinTemplate', verbose_name="шаблон", on_delete=models.CASCADE, blank=True, null=True)
  
  name     = models.CharField(verbose_name='Имя',max_length=120, blank=True, null=True)
  email    = models.CharField(max_length=120, blank=True, null=True)
  phone    = models.CharField(verbose_name='Номер телефона',max_length=120, blank=True, null=True)
  address  = models.CharField(verbose_name='Адрес',max_length=120, blank=True, null=True)
  comments = models.TextField(verbose_name='Коментарии',blank=True, null=True, default=None)
  # order    = models.ForeignKey('order.Order', related_name="napkins",on_delete=models.CASCADE, blank=True, null=True)
  ordered  = models.BooleanField(default=False)
  status    = models.CharField(max_length=120, blank=True, null=True, choices=NAPKIN_STATUS_CHOICES) 
  created  = models.DateTimeField(verbose_name='Дата создания',auto_now_add=True, auto_now=False, blank=True, null=True)
  updated  = models.DateTimeField(verbose_name='Дата обновления',auto_now_add=False, auto_now=True, blank=True, null=True)
  def __str__(self):
    try:
      return f'sk:{self.sk}|\nlogo:{self.logo}|\ntemplate:{self.template}'
    except Exception as e:
      return f'{self.logo}'


class NapkinTemplate(models.Model):
  image       = models.ImageField(blank=True, null=True)
  colour      = models.ForeignKey('constructor.Colour',     blank=True, null=True, on_delete=models.CASCADE)
  form_factor = models.ForeignKey('constructor.FormFactor', blank=True, null=True, on_delete=models.CASCADE)
  embossing   = models.ForeignKey('constructor.Embossing',  blank=True, null=True, on_delete=models.CASCADE)
  folding     = models.ForeignKey('constructor.Folding',    blank=True, null=True, on_delete=models.CASCADE)
  default     = models.BooleanField(default=False)
  def __str__(self): return f'{self.image}'


class Colour(models.Model):
  name = models.CharField(max_length=20, blank=True, null=True)
  code = models.CharField(max_length=20, blank=True, null=True)
  rgb  = models.CharField(max_length=20, blank=True, null=True)
  def __str__(self):
    return f'{self.name}|{self.code}|{self.rgb}'


class FormFactor(models.Model):
  name = models.CharField(max_length=20)
  code = models.CharField(max_length=20, blank=True, null=True)
  def __str__(self):
    return f'{self.name}|{self.code}'


class Embossing(models.Model):
  name = models.CharField(max_length=20)
  code = models.CharField(max_length=20, blank=True, null=True)
  image= models.ImageField(blank=True, null=True)
  def __str__(self):
    return f'{self.name}|{self.code}'


class Folding(models.Model):
  name = models.CharField(max_length=20)
  code = models.CharField(max_length=20, blank=True, null=True)
  image= models.ImageField(blank=True, null=True)
  def __str__(self):
    return f'{self.name}'

margo/order/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from django.utils.translation import gettext as _
from cart.models import CartItem
User = get_user_model()


ORDER_STATUS_CHOICES = (
	(_('Принят в обработку'), _('Принят в обработку')),
	(_('Выполняется'), _('Выполняется')),
	(_('Выполнен'), _('Выполнен')),
	# (_('Оплачен'), _('Оплачен')),
)


class Status(models.Model):
  name = models.CharField(max_length=24, blank=True, null=True, default=None)
  is_active = models.BooleanField(default=True)
  created = models.DateTimeField(auto_now_add=True, auto_now=False)
  updated = models.DateTimeField(auto_now_add=False, auto_now=True)
  def __str__(self):
    return "Статус %s" % self.name
  class Meta: verbose_name = 'Статус'; verbose_name_plural = 'Статусы'; 


class OrderItemManager(models.Manager):
  def all(self):
    return super(OrderItemManager, self).get_queryset().filter(ordered=False)


class OrderItem(models.Model):
  user           = models.ForeignKey(User, verbose_name='Пользователь',on_delete=models.CASCADE, blank=True, null=True)
  sk             = models.CharField(max_length=120, verbose_name='Ключ сессии',blank=True, null=True)
  item           = models.ForeignKey('item.Item', verbose_name='Товар',on_delete=models.CASCADE, blank=True, null=True)
  order          = models.ForeignKey('order.Order', related_name='items', verbose_name='Заказ',on_delete=models.CASCADE, blank=True, null=True)
  size           = models.CharField(verbose_name='Размер',max_length=20, blank=True, null=True)
  quantity       = models.IntegerField(verbose_name='Количество',default=1)
  price_per_item = models.DecimalField(verbose_name='Цена за шт.',max_digits=10, decimal_places=2, blank=True, null=True)
  total_price    = models.DecimalField(verbose_name='Суммарная стоимость',max_digits=10, decimal_places=2, blank=True, null=True)
  ordered        = models.BooleanField(verbose_name='Заказан ли?',default=False, blank=True, null=True)
  created        = models.DateTimeField(verbose_name='Дата создания',auto_now_add=True, auto_now=False, blank=True, null=True)
  updated        = models.DateTimeField(verbose_name='Дата обновления',auto_now_add=False, auto_now=True, blank=True, null=True)
  # objects        = OrderItemManager()
  def __str__(self):
    return f'{self.item.name}, {self.quantity}штука, {self.total_price}'
  def save(self, *args, **kwargs):
    price_per_item = self.item.price
    self.price_per_item = price_per_item
    self.total_price = self.quantity * price_per_item
    super().save(*args, **kwargs)
  class Meta: verbose_name = 'Товар в заказе'; verbose_name_plural = 'Товары в заказе'; 


class Order(models.Model):
  user        = models.ForeignKey(User, verbose_name='Пользователь',on_delete=models.CASCADE, blank=True, null=True)
  sk          = models.CharField(verbose_name='Ключ сессии',max_length=120)
  total_price = models.DecimalField(verbose_name='Стоимость',max_digits=10, decimal_places=2, default=0)
  name        = models.CharField(verbose_name='Имя',max_length=120, blank=True, null=True)
  email       = models.CharField(max_length=120, blank=True, null=True)
  phone       = models.CharField(verbose_name='Номер телефона',max_length=120, blank=True, null=True)
  address     = models.CharField(verbose_name='Адрес',max_length=120, blank=True, null=True)
  comments    = models.TextField(verbose_name='Коментарии',blank=True, null=True, default=None)
  delivery    = models.CharField(max_length=120, verbose_name="Способ доставки", blank=True, null=True, ) 
  payment_way = models.CharField(max_length=120, verbose_name="Оплата", blank=True, null=True, ) 
  status      = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, blank=True, null=True) 
  created     = models.DateTimeField(verbose_name='Дата создания',auto_now_add=True, auto_now=False, blank=True, null=True)
  updated     = models.DateTimeField(verbose_name='Дата обновления',auto_now_add=False, auto_now=True, blank=True, null=True)
  class Meta: verbose_name = 'Заказ'; verbose_name_plural = 'Заказы'; 
  def __str__(self):
    return f'{self.phone}|{self.name}|{self.email}|{self.address}' 

margo/order/forms.py
from django import forms

PAYMENT_CHOICES = (
    ('manager', 'Предзаказ у менеджера'),
    ('privat', 'Предоплата на картку Приват24'),
)
CITY_CHOICES = (
  ('Львів', 'Львів'),
  ("Винники", "Винники"),
  ("Рудно", "Рудно"),
  ("Зимна Вода", "Зимна Вода"),
  ("Лапаївка", "Лапаївка"),
  ("Холодновідка", "Холодновідка"),
  ("Старе", "Старе Рудно"),
  ("Скнилів", "Скнилів"),
  ("Солонка", "Солонка"),
  ("Сокільники", "Сокільники"),
  ("Брюховичі", "Брюховичі"),
)
SHIPPING_CHOICES = (
  ('Адресна доставка','Адресна доставка'),
  ('Перевізник','Перевізник'),
  ('По Львову','По Львову'),
  ('Поштомат','Поштомат'),
)

class CheckoutForm(forms.Form):
  name =  forms.CharField(label="П.І.Б", max_length=100, required=False, widget=forms.TextInput(attrs={  'style':'color:black;'}))
  email =  forms.CharField(label="Email-адреса", max_length=100, required=False, widget=forms.TextInput(attrs={  'style':'color:black;'}))
  address =  forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={  'style':'color:black;'}))
  phone           = forms.CharField(
    label="Номер телефону", 
    widget=forms.TextInput(
      attrs={
        'style':'color:black;',
        # 'placeholder':"Телефон",
      }
    ),
  )
  city            = forms.ChoiceField(choices=CITY_CHOICES, label="Місто", widget=forms.TextInput(attrs={  'style':'color:black;'}))
  street          = forms.CharField(label="Адреса доставки", widget=forms.TextInput(attrs={  'style':'color:black;'}))
  # shipping        = forms.ChoiceField(choices=SHIPPING_CHOICES, label="Спосіб доставки", widget=forms.Select(attrs={  'style':'color:black;'}))
  shipping        = forms.ChoiceField(choices=SHIPPING_CHOICES, label="Спосіб доставки",widget=forms.Select(attrs={  'style':'color:black;'}))
  payment_option  = forms.ChoiceField(choices=PAYMENT_CHOICES, widget=forms.Select(attrs={  'style':'color:black;'}), label="Спосіб оплати")
  comment         = forms.CharField(label="Ваше повідомлення(коментар)", widget=forms.Textarea(attrs={'rows': 5, 'cols': 40,'style':'color:black;'}))

margo/order/views.py
from django.urls import path
from django.shortcuts import (render, get_object_or_404, reverse, redirect)
from order.forms import (CheckoutForm)
from django.contrib import messages
from order.models import Order, OrderItem
from cart.models import CartItem
from django.views.generic import View
from utils.utils import get_sk, get_user
from django.http import HttpResponse, JsonResponse
from utils.utils import send_order_mail
from constructor.models import Napkin


def order_items(request):
  flag = 'items'
  if request.method == 'GET':
    cart_items = CartItem.objects.filter(sk=get_sk(request), ordered=False).exists()
    if not cart_items:
      referer = request.META.get('HTTP_REFERER', '/')
      return redirect(referer)
    return render(request, 'checkout.html', locals())
  sk            = get_sk(request)
  name          = request.POST.get('name', '')
  phone         = request.POST.get('phone', '')
  email         = request.POST.get('email', '')
  comments      = request.POST.get('comment', '')
  address       = request.POST.get('address', '')
  payment       = request.POST.get('payment', '')
  delivery      = request.POST.get('delivery', '')
  order         = Order()
  order.name    = name
  order.email   = email
  order.address = address
  order.phone   = phone
  order.comments= comments 
  order.payment_way = payment
  order.delivery= delivery
  order.sk      = sk
  order.save()

  create_order_items(request, order)
  order.save()
  if payment == 'privat':
    return redirect("pay")
  elif payment == 'manager':
    send_order_mail()
    return redirect('thank_you')



def order_napkin(request):
  flag = 'napkin'
  if request.method == 'GET':
    napkins = Napkin.objects.filter(sk=get_sk(request), ordered=False).exists()
    if not napkins:
      referer = request.META.get('HTTP_REFERER', '/')
      return redirect(referer)
    return render(request, 'checkout.html', locals())
  sk            = get_sk(request)
  name          = request.POST.get('name', '')
  phone         = request.POST.get('phone', '')
  email         = request.POST.get('email', '')
  comments      = request.POST.get('comment', '')
  address       = request.POST.get('address', '')
  payment       = request.POST.get('payment', '')
  delivery      = request.POST.get('delivery', '')
  napkin         = Napkin.objects.get(sk=sk, ordered=False)
  napkin.name    = name
  napkin.email   = email
  napkin.address = address
  napkin.phone   = phone
  napkin.comments= comments 
  napkin.sk      = sk
  napkin.ordered=True
  # 111111111111@gmail.com
  napkin.save()
  send_order_mail()
  # send_napkin_mail()
  return redirect('thank_you')


def create_order(request):
  return order, payment


def create_order_items(request, order):
  sk = get_sk(request)
  total_price = 0
  for cart_item in CartItem.objects.filter(ordered=False, sk=sk):
    total_price += cart_item.total_price
  order.total_price = total_price

  cart_items = CartItem.objects.filter(sk=sk)
  if request.user.is_authenticated:
    order.user = request.user
    cart_items.update(user=request.user)

  order.save()
  cart_items.update(order=order)

  for cart_item in CartItem.objects.filter(sk=sk, ordered=False):
    order_item = OrderItem()
    order_item.item = cart_item.item 
    order_item.user = cart_item.user 
    order_item.sk = cart_item.sk 
    order_item.order = cart_item.order 
    # order_item.size = cart_item.size 
    order_item.quantity = cart_item.quantity 
    order_item.price_per_item = cart_item.price_per_item 
    order_item.total_price = cart_item.total_price 
    order_item.save()
  cart_items.update(ordered=True)
  # cart_items.delete()

margo/templates/includes/basket.html
{% load i18n %}
<div id="basket" class="basket" style="display:none;">
    <div class="basket__wrap">
        <div class="basket__header">
            <div class="basket_title">Корзина товарів</div>
            <div class="basket_close cross"></div>
        </div>
        <div class="basket__box">
        <form action="" class="cart_items_form basket_form">
        </form>
        </div>
        <div class="basket__footer basket__footer-shopping">
            <div class="continue_shopping">Продовжити покупки</div>
            <form class="checkout_button" action="{% url 'order_items' %}">
                <input class="basket__footer_btn btn" type="submit" value="{% trans 'Оформити замовлення' %}">
            </form>
        </div>
    </div>
</div>

margo/templates/includes/catalog.html
{% load i18n %}
<section class="container catalog">
  <div class="container__header">
      <h2 class="container__title">{% trans 'Вітирна товарів' %}</h2>
  </div>
  <div class="catalog__box">
      <div class="catalog__wrap">
        <!-- 
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %}
        {% include 'includes/catalog_item_card.html' %} 
        -->
      </div>
      {% if MORE%}
      <div data-href="" class="btn catalog__btn show_more">{% trans 'Більше товарів' %}</div>
      {% endif %}
  </div>
</section>
<script src="/static/catalog.js"></script>

margo/templates/includes/category.html
<section class="container container_top catalog">
    <div class="container__header">
        <h1 class="container__title">{{category.title}}</h1>
    </div>
    <div class="catalog__box">
        <div class="catalog__servise">
            {% include 'includes/filter.html' %}
            {% include 'includes/sort.html' %}
        </div>
        <div class="catalog__wrap">
        </div>
        {% include 'includes/pagination.html' %}
    </div>
</section>

margo/templates/includes/contacts.html
{% load i18n %}
<div class="container_top   hero">
<div class="hero__main">
    <div class="hero__section contact-adrees__section">
    <h1 class="hero__section_title">{% trans "Наші контакти" %}</h1>
    <div class="hero__section_text">
        <p>  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
    <div class="hero__section_adrees contact-adrees">
        <div class="contact-adrees__item contact-adrees__item-email"><a href="mailto:marketing@tissueclub.com">marketing@tissueclub.com</a></div>
        <div class="contact-adrees__item contact-adrees__item-phone"><a href="tel:+380352434361"> +38 (0352) 43-43-61 </a></div>
        <div class="contact-adrees__item contact-adrees__item-map"><a href="https://goo.gl/maps/brNZAUyL6Jn2X5nB6">вул. Зелена, 15, с. Петрикiв, Тернопiльський р-н, Тернопiльська обл.</a></div>
    </div>
    </div>
    <div class="hero__section">
    </div>
</div>
<div class="hero__box">
    <h2 class="hero__box_title">{% trans "Виникли запитання?" %}</h2>
    <p class="hero__box_subtitle">{% trans "Заповніть форму нижче і ми дамо Вам відповідь в найближчий час!" %}</p>
    <form class="hero__form form contact_form" action="{% url 'user_contact' %}" method='POST'>
    {% csrf_token %}
    <div class="form__container">
        <div class="form__container_img">
        <object type="image/svg+xml" data="/static/img/svg/email.svg"  ></object>
        </div>
        <input class="form__container_input input_text email" type="email" name="email" value="" placeholder="E-mail ">
    </div>
    <div class="form__container">
        <div class="form__container_img">
        <object type="image/svg+xml" data="/static/img/svg/phone-call.svg"></object>
        </div>
        <input class="form__container_input input_text tel" type="tel" name="tel" value="" placeholder="{% trans 'Номер телефону' %}">
    </div>
    <div class="form__container-text">
    <textarea  class="form__container_textarea" rows="10" cols="45" name="text"></textarea>
    </div>
    <input type="hidden" name="request_type" value="Замовити дзвінок">
    <input class="form__container_control btn" type="submit" name="button">{% trans "Замовити дзвінок" %}</input>
    </form>
</div>
</div>
<div style="margin-top:200px;"></div>

margo/templates/includes/favours.html
{% load i18n %}
<div id="like_list" class="basket" style="display:none;">
    <div class="basket__wrap">
        <div class="basket__header">
            <div class="basket_title">{% trans "Список бажань" %}</div>
            <div class="basket_close cross"></div>
        </div>
        <div class="basket__box favour_items_box">
        </div>
        <div class="basket__footer basket__footer-like">
            <div class="basket__footer_btn btn add_all_favours_button">{% trans "Додати в кошик все" %}</div>
        </div>
    </div>
</div>

margo/templates/includes/horeca_hero.html
{% load i18n %}
<div class="    hero">
    <div class="hero__main">
        <div class="hero__section">
            <h1 class="hero__section_title">Horeca</h1>
            <div class="hero__section_text">

                <p> Вам потрібні серветки для столу і ви бажаєте співпрацювати з надійним дистриб'ютором господарських товарів для сфери відпочинку та громадського харчування? Ми раді запропонувати свою співпрацю! інтернет-магазин хозтоварів Марго бере до уваги побажання своїх клієнтів. Тому серед барної продукції для індустрії гостинності HoReCa була створена окрема підкатегорія, де представлені товари цього напрямку. Мы гарантуємо, що на нашому сайті Ви можете швидко і легко замовити паперові серветки оптом, попередньо обравши те, що вам потрібно!</p>
                <p>Широкий асортимент продукції для сервірування столу! Серветки з фруктами Horeca, Серветки з малюнком та багато іншого. Зробіть вдалий вибір барних серветок для столу! Оптові ціни! Залишіть свої дані і ми вам перезвонимо.
                </p>
                <p>Доставка хозтоварів оптом по Україні через інтернет-магазин здійснюється протягом 2 днів. У нас хороші умови доставки, якщо Ви бажаєте купити серветки в Тернополі або Тернопільскій області! Придбайте оптом - безкоштовна доставка по Україні! Марго надійно працює з 2004 року!
                </p>

            </div>
        </div>
        <div class="hero__section">

        </div>
    </div>
    <div class="hero__footer">
        <div class="hero__footer_title">{% trans 'Довірте виготовлення продукції власної торгової марки саме нам!' %}</div>
        <div class="hero__footer_box">
            <div class="hero__footer_item experens"> {% trans 'Асортимент' %}</div>
            <div class="hero__footer_item quality">  {% trans 'Ціни' %}</div>
            <div class="hero__footer_item stability">{% trans 'Доставка' %} </div>
        </div>
    </div>

    <div class="hero__box">
        <img class="hero__form_img" src="/static/img/private_label.png" alt="Private Label">
        <form class="hero__form form" action="{% url 'user_contact' %}" method="POST">
        {% csrf_token %}

            <div class="form__container">
                <div class="form__container_img">
                    <object type="image/svg+xml" data="/static/img/svg/email.svg"></object>
                </div>
                <input class="form__container_input input_text" type="email" name="email" value="" placeholder="E-mail ">
            </div>
            <div class="form__container">
                <div class="form__container_img">
                    <object type="image/svg+xml" data="/static/img/svg/phone-call.svg"></object>
                </div>
                <input class="form__container_input input_text" type="tel" name="tel" value="" placeholder="Номер телефону">
                <input type="hidden" name='request_type' value="Horeca">
            </div>
            <input class="form__container_control btn" type="submit" value="{% trans 'Замовити дзвінок' %}" name="button"> </input>
        </form>
    </div>
</div>

margo/templates/includes/order_form.html
{% load i18n %}
<section class="container_top">
    <div class="container_top ordering">
        <h2>Оформлення замовлення</h2>
        <form style=" " method="POST" action="." class="make_order_form ">
            {% csrf_token %}

            <input type="hidden" name="name"     value="">
            <input type="hidden" name="phone"    value="">
            <input type="hidden" name="email"    value="">
            <input type="hidden" name="comment"  value="">
            <input type="hidden" name="address"  value="">
            <input type="hidden" name="payment"  value="">
            <input type="hidden" name="delivery" value="">

            <div class="ordering__section-group ordering__section-group-input">

                <div class="form-group form-group-colum">
                <label for="username" class="sr-only">  П.І.Б</label>
                <input type="text" class="form-control name"  id="username" placeholder="П.І.Б" autocomplete="off">
                    <span class="form-group_error">{% trans "Обязательно для заполнения" %}</span>
                </div>

                <div class="form-group form-group-colum">
                <label for="username" class="sr-only">Email-адреса</label>
                <input type="email" class="form-control email" id="email" placeholder="Email-адреса" data-validate autocomplete="off">
                    <span class="form-group_error">{% trans "Обязательно для заполнения" %}</span>
                </div>

                <div class="form-group form-group-colum">
                <label for="username" class="sr-only">Номер телефону</label>
                <input type="tel" class="form-control phone" id="phone" placeholder="Номер телефону" data-validate autocomplete="off">
                    <span class="form-group_error">{% trans "Обязательно для заполнения" %}</span>
                </div>

                <div class="form-group form-group-colum">
                <label for="username" class="sr-only">{% trans "Адреса доставки" %}</label>
                <input type="text" class="form-control address" id="address" placeholder="Адрес" autocomplete="off">
                </div>

            </div>
            <div class="ordering__section-group ordering__section-group-textarea">

                <div id="div_id_comment " class="form-group form-group-colum">
                    <textarea cols="40" rows="30" class="textarea form-control-text comment" placeholder="{% trans 'Ваше повідомлення (коментар)' %}'" required="" id="id_comment"></textarea>
                </div>

            </div>
            <div class="ordering__section-group ordering__section-group-mod ordering__section-group-list">

                <div class="form-group">
                <div class="select__box">
                    <div class="select_title">{% trans "Спосіб доставки" %}:</div>
                    <div class="select__group select__view">
                        <div class="select_value">
                            <div class="select_value_name delivery" data-id="samovyviz">{% trans "Самовивіз" %}</div>
                            <div class="select_value_control">
                                <span class=" arrow_bottom"></span>
                            </div>
                        </div>
                        <div class="select__items">
                            <div class="select__item" data-id="urkposhta">{% trans "Укрпочта" %}</div>
                            <div class="select__item" data-id="novaposhta">{% trans "Нова Почта" %}</div>
                        </div>
                    </div>
                </div>
                </div>
                {% if not flag == "napkin" %}
                <div class="form-group">
                <div class="select__box">
                    <div class="select_title">{% trans "Спосіб оплати" %}:</div>
                    <div class="select__group select__view">
                        <div class="select_value">
                            <div class="select_value_name payment" data-id="privat">{% trans "Приват24" %}</div>
                            <div class="select_value_control">
                                <span class=" arrow_bottom"></span>
                            </div>
                        </div>
                        <div class="select__items">
                            <div class="select__item" data-id="manager">{% trans "Менеджер" %}</div>
                        </div>
                    </div>
                </div>
                </div>
                {% endif %}

            </div>
            <div class="ordering__section-group ordering__section-group-btn">

                <div class="form-group form-group-btn">
                    <input class="btn" type="submit" id="ordering_form" value="Оформити замовлення">
                </div>

            </div>
        </form>
    </div>
</section>

<script>
  document.addEventListener('DOMContentLoaded', function(){
    $('#ordering_form').on('click', (e) => {
      e.preventDefault();
      name     = $('.name').val()
      email    = $('.email').val()
      phone    = $('.phone').val()
      address  = $('.address').val()
      comment  = $('.comment').val()
      payment  = $('.payment').data('id')//.text();
      delivery = $('.delivery').data('id')//.text();
      hidden_name     = $("input[name=name]")
      hidden_phone    = $("input[name=phone]")
      hidden_email    = $("input[name=email]")
      hidden_comment  = $("input[name=comment]")
      hidden_address  = $("input[name=address]")
      hidden_payment  = $("input[name=payment]")
      hidden_delivery = $("input[name=delivery]")
      hidden_name.val(name)
      hidden_phone.val(phone)
      hidden_email.val(email)
      hidden_comment.val(comment)
      hidden_address.val(address)
      hidden_payment.val(payment)
      hidden_delivery.val(delivery)
      $('.make_order_form').submit();
    })
  })
  </script>